### ISSUE TITLE
Failing to process files after update from 2.0.3 to 2.1.0 

### ISSUE THREAD

**Issue by yofreke** [nippur72/ifdef-loader#20]
Our CI started failing today after this update.  Depending on the build, some files are not having the `ifdef` comments processed.

Example build logs:

```
...

[01:14:09][Step 4/7] ERROR in ./src/mvc/model/PlatformModel.js
[01:14:09][Step 4/7] Module build failed: Duplicate declaration "ledgerPromise"
[01:14:09][Step 4/7] 
[01:14:09][Step 4/7]   1010 |     });
[01:14:09][Step 4/7]   1011 |     /// #else
[01:14:09][Step 4/7] > 1012 |     const ledgerPromise = ledger.runPurchaseFunction(config.purchaseFunction, purchaseCopy);
[01:14:09][Step 4/7]        |           ^
[01:14:09][Step 4/7]   1013 |     /// #endif
[01:14:09][Step 4/7]   1014 | 
[01:14:09][Step 4/7]   1015 |     return ledgerPromise.then(
[01:14:09][Step 4/7] 
[01:14:09][Step 4/7] BabelLoaderError: Duplicate declaration "ledgerPromise"
[01:14:09][Step 4/7] 
[01:14:09][Step 4/7]   1010 |     });
[01:14:09][Step 4/7]   1011 |     /// #else
[01:14:09][Step 4/7] > 1012 |     const ledgerPromise = ledger.runPurchaseFunction(config.purchaseFunction, purchaseCopy);
[01:14:09][Step 4/7]        |           ^
[01:14:09][Step 4/7]   1013 |     /// #endif
[01:14:09][Step 4/7]   1014 | 
[01:14:09][Step 4/7]   1015 |     return ledgerPromise.then(
[01:14:09][Step 4/7] 
[01:14:09][Step 4/7]     at transpile (/Users/teamcityAgent2/workspace/buildAgent/work/e12c3c134554c23d/frontend/node_modules/babel-loader/lib/index.js:65:13)
[01:14:09][Step 4/7]     at /Users/teamcityAgent2/workspace/buildAgent/work/e12c3c134554c23d/frontend/node_modules/babel-loader/lib/fs-cache.js:118:18
[01:14:09][Step 4/7]     at ReadFileContext.<anonymous> (/Users/teamcityAgent2/workspace/buildAgent/work/e12c3c134554c23d/frontend/node_modules/babel-loader/lib/fs-cache.js:31:21)
[01:14:09][Step 4/7]     at ReadFileContext.callback (/Users/teamcityAgent2/workspace/buildAgent/work/e12c3c134554c23d/frontend/node_modules/graceful-fs/graceful-fs.js:90:16)
[01:14:09][Step 4/7]     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
[01:14:09][Step 4/7]  @ ./src/Application.js 129:21-59

...
```

**Comment by GWigWam** [comment]
Could you provide one of theses files in which it's not working? (`PlatformModel.js` maybe?)

**Comment by GWigWam** [comment]
Hey @nippur72 it seems the deploy of `v2.1.0` isn't working. When I download the version using NPM the `preprocessor.js` file is still an old version. I don't think my new version of `preprocessor.ts` was compiled properly, or it wasn't included in the release to npm.

**Comment by nippur72** [comment]
yes, for some reason the `.js` wasn't added to the npm package -- which in turn makes me wonder why @yofreke is experiencing the error since I assume he's still using the old JavaScript file.

Anyway I've created a clean `2.1.1` which includes a better `.npmignore` (e.g. test files are left out).

@yofreke can you please report if you are still get the issue with the `2.1.1`?

**Comment by yofreke** [comment]
2.1.1 is looking good for me, no issues building the same project

**Comment by nippur72** [comment]
thanks and sorry for the inconvenience
